/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ShapeService } from "../shape.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ShapeCreateInput } from "./ShapeCreateInput";
import { Shape } from "./Shape";
import { ShapeFindManyArgs } from "./ShapeFindManyArgs";
import { ShapeWhereUniqueInput } from "./ShapeWhereUniqueInput";
import { ShapeUpdateInput } from "./ShapeUpdateInput";
import { ShapeInput } from "../ShapeInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ShapeControllerBase {
  constructor(
    protected readonly service: ShapeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Shape })
  @nestAccessControl.UseRoles({
    resource: "Shape",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createShape(@common.Body() data: ShapeCreateInput): Promise<Shape> {
    return await this.service.createShape({
      data: {
        ...data,

        image: data.image
          ? {
              connect: data.image,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        attributes: true,
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        positionX: true,
        positionY: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Shape] })
  @ApiNestedQuery(ShapeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Shape",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shapes(@common.Req() request: Request): Promise<Shape[]> {
    const args = plainToClass(ShapeFindManyArgs, request.query);
    return this.service.shapes({
      ...args,
      select: {
        attributes: true,
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        positionX: true,
        positionY: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Shape })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Shape",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shape(
    @common.Param() params: ShapeWhereUniqueInput
  ): Promise<Shape | null> {
    const result = await this.service.shape({
      where: params,
      select: {
        attributes: true,
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        positionX: true,
        positionY: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Shape })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Shape",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateShape(
    @common.Param() params: ShapeWhereUniqueInput,
    @common.Body() data: ShapeUpdateInput
  ): Promise<Shape | null> {
    try {
      return await this.service.updateShape({
        where: params,
        data: {
          ...data,

          image: data.image
            ? {
                connect: data.image,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          attributes: true,
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          positionX: true,
          positionY: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Shape })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Shape",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteShape(
    @common.Param() params: ShapeWhereUniqueInput
  ): Promise<Shape | null> {
    try {
      return await this.service.deleteShape({
        where: params,
        select: {
          attributes: true,
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          positionX: true,
          positionY: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/draw-shape-on-image")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async DrawShapeOnImage(
    @common.Body()
    body: ShapeInput
  ): Promise<string> {
    return this.service.DrawShapeOnImage(body);
  }
}
